### ISSUE TITLE
Missing multi-species tracking functionality

### ISSUE THREAD

**Issue by maxtopp-mugglestone** [xsuite/xpart#103]
Xsuite tracking did not appear to respond to the 'chi', 'charge ratio', or 'mass ratio' keywords (i.e. particles assigned with different values of these inputs exhibited the same deflection when tracked through a dipole). 

Editing build_particles.py to add chi as a keyword argument to the build_particles function and adding 
    part_dict['chi'] = chi
inside the function appeared to restore the missing functionality.

**Comment by maxtopp-mugglestone** [comment]
mass_ratio is also missing from the function _update_chi_charge_ratio. Issue can be fixed by adding to the function:
        self._setattr_if_consistent('mass_ratio',
                                    given_value=mass_ratio,
                                    computed_value=_mass_ratio,
                                    mask=mask)

**Comment by giadarol** [comment]
this should be solved in the present version.

Don't hesitate to reopen if you still see issues
