### ISSUE TITLE
particles.tau doesn't exists

### ISSUE THREAD

**Issue by pbelange** [xsuite/xpart#35]
Running a simple `xp.generate_matched_gaussian_bunch()` example, particles are created correctly, `particles.zeta` exists but `particles.tau` doesn't.

Code from https://xsuite.readthedocs.io/en/latest/particlesmanip.html, section [Example: Gaussian bunch]

**Comment by giadarol** [comment]
I would like to expose only zeta to make the user aware that this is the variable that is actually stored in memory
